import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/src/shared/header/Header";
import { ViewTransition } from "react";

const inter = Inter({
  variable: "--font-inter", // Puedes usar una variable CSS personalizada
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Redex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <Header>
            {children}
        </Header>
      </body>
    </html>
  );
}
